# Generated by Django 3.0.6 on 2020-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_date', models.DateTimeField()),
            ],
        ),
    ]
