# Generated by Django 3.0.6 on 2020-05-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0002_timerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRecord',
        ),
    ]
